name: "mirror repo projects"
on: # run this on a cron schedule
  schedule:
    - cron: '*/5 * * * *'
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        source_column_id: MDEzOlByb2plY3RDb2x1bW44NTA2NzUz
        target_column_id: MDEzOlByb2plY3RDb2x1bW44NTA2NzYw
        github_token: ${{ secrets.TEST_SECRET }}
